### ISSUE TITLE
Brak w acad drzwi typu samozamykacz, elektrotrzymacz i inne

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#1]
Brak odpowiednich drzwi w

**Comment by mimooh** [comment]
test

-- 
Karol Kreński
tel. 517-302-055

**Comment by fliszer** [comment]
Jaka ma być finalna struktura rysowania tych drzwi, tj. z jakich poziomów
CDOOR -> jakie mają być nazwy?
CROOM -> CDOOR -> ??

**Comment by akrasuski** [comment]
Może tak:
CDOOR
a potem:
DCLOSER
DELECTRIC
DPLAIN

i jeszcze ten VVENT to są dziury w suficie lub podłodze

**Comment by fliszer** [comment]
Zrobione - dodałem komendę CDOOR z możliwością wyboru typu drzwi ...
W katalogu jest folder release, w którym wrzucam aktualną bibliotekę ...

**Comment by fliszer** [comment]
@mimooh przy eksporcie pojawią ci się obiekty DC, DE, DP, które odpowiednio oznaczają closer, electric, plain

**Comment by akrasuski** [comment]
A biblioteczkę z svn, czy skąd?

**Comment by fliszer** [comment]
@akrasuski czytaj do końca moje wiadomości ;)

> W katalogu jest folder release, w którym wrzucam aktualną bibliotekę ...

może faktycznie za duże uproszczenie zastosowałem: 
svn/autocad/release/wizFDS.dll

**Comment by mimooh** [comment]
Ja juz mam w wielu miejscach D (door), E (electromagnet), C (closer).
Mozesz tak przerobic Twoje DC, DE, DP?

-- 
Karol Kreński
tel. 517-302-055

**Comment by fliszer** [comment]
Done. 

Przy eksporcie będziesz miał D, E, C ...

Wrzuciłem nową dll
