### ISSUE TITLE
Problem z parserem plików csv

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#11]
@mimooh 
sqlite3.OperationalError: table simo_csv has 40 columns but 42 values were supplied

Nie wiem dlaczego ale z pliku csv złapał jeszcze dwa dodatkowe atrybuty LLN2: 

OrderedDict([('CEILT', None), ('DJET', 0), ('FLHGT', None), ('FLOORT', None), ('HGT', 2), ('HRR', None), ('HRRL', None), ('HRRU', None), ('IGN', None), ('LLCO', 0), ('LLCO2', 0), ('LLH2O', 0), ('LLHCL', 0), ('LLHCN', 0), ('LLN2', None), ('LLO2', 20), ('LLOD', 0), ('LLT', 15), ('LLTS', 0), ('LLTUHC', 0), ('LWALLT', None), ('PLUM', None), ('PRS', -15), ('PYROL', None), ('TRACE', None), ('ULCO', 0), ('ULCO2', 0), ('ULH2O', 0), ('ULHCL', 0), ('ULHCN', 0), ('ULN2', None), ('ULO2', 20), ('ULOD', 0), ('ULT', 16), ('ULTS', 0), ('ULTUHC', 0), ('UWALLT', None), ('VOL', 0), **('ULN29', 78), ('LLN29', 78)])**

**Comment by mimooh** [comment]
gotowe
