### ISSUE TITLE
Spięcie simo z GUI

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#19]
Zapisanie obiektów autocad.json, kofiguracja.json użytkownika ze GUI, uruchomienie pliku pythona do rozpoczęcia symulacji.

**Comment by fliszer** [comment]
@mimooh lub @akrasuski podeślijcie mi gdzie leżą dobre pliki wejściowe do simo i jak uruchamiacie skrypt pythona

**Comment by akrasuski** [comment]
svn_mimooh/simo/stable/server/
uruchamiasz simo.py confSimo.json
z tym, że confSimo.json przychodzi jako zrzut tego co ludzie wpiszą w GUI

**Comment by akrasuski** [comment]
W jakimś stopniu zrobione
