### ISSUE TITLE
Uporządkowanie i uzupełnienie rozkładów

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#25]
Pogrupowanie rozkładów w pliku distributions.json w układzie typu budynków. Uzupełnienie rozkładów dla budynku typu biuro, centrum handlowe, hotel.

**Comment by mimooh** [comment]
Ja zrobie. Patrzylem jak by to mialo w yaml wygladac, ktory jest generalnie bardziej czytelny, ale jednak w jsonie ladniej to wyglada.

**Comment by mimooh** [comment]
@akrasuski, zobacz stable/server/new_distributions.json. Zobacz czy ta koncepcja Ci pasuje, albo zmien co Ci tam potrzeba. Jak juz ten nowy format poblogoslawimy (daj znac) to nalezy go skopiowac do naszych galezi i od tej pory na takim wejsciowym distributions pracowac.

**Comment by akrasuski** [comment]
Zmieniamy na to co zaproponowałeś. Dla mnie jest ok. Może jeszcze zastanowić się confSimo.json czy coś zmieniamy.

**Comment by mimooh** [comment]
gotowe
