### ISSUE TITLE
Dodanie możliwości nazywania pliku wynikowego z ac

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#34]
Byłoby fajnie, gdyby udało się dodać możliwość nadawania nazwy pliku wychodzącego z cexport. Dodatkowo fajnie jakby ten plik miał rozszerzenie json.

**Comment by fliszer** [comment]
Done. Można zamykać.

Sent from gmail mobile ...

21.02.2017 6:02 PM "akrasuski" <notifications@github.com> napisał(a):
