### ISSUE TITLE
[Web] Definicja jet-fan'a

### ISSUE THREAD

**Issue by fliszer** [akrasuski/simo#42]
@milnicki3 poniżej jest definicja dwóch jet'ów:

```
&RAMP ID='rampwent', T=1, F=0 /
&RAMP ID='rampwent', T=5, F=1 /

&DEVC ID='dTemp1', XYZ=0.9,0.15,2.1, QUANTITY='TEMPERATURE',  SETPOINT=343,  INITIAL_STATE=.TRUE. /

&OBST XB=0, 1.8, 0, 0.3, 2.1, 2.4, COLOR='SILVER', DEVC_ID='dTemp1' /
&VENT XB=0, 0, 0, 0.3, 2.1, 2.4, SURF_ID='HVAC', ID='IN1', COLOR='GRAY'/
&VENT XB=1.8, 1.8, 0, 0.3, 2.1, 2.4, SURF_ID='HVAC', ID='OUT1', UVW=0,0,0, COLOR='BLUE'/
&HVAC ID='IN1', TYPE_ID='NODE', DUCT_ID='JETFAN1', VENT_ID='IN1'/
&HVAC ID='OUT1', TYPE_ID='NODE', DUCT_ID='JETFAN1', VENT_ID='OUT1'/
&HVAC ID='JETFAN1', TYPE_ID='DUCT', NODE_ID='IN1','OUT1', VOLUME_FLOW=1.633, AREA=0.1, RAMP_ID='rampwent' /


&DEVC ID='dTemp2', XYZ=0.9, 10.15, 2.1, QUANTITY='TEMPERATURE',  SETPOINT=343,  INITIAL_STATE=.TRUE. /

&OBST XB=0, 1.8, 10, 10.3, 2.1, 2.4, COLOR='SILVER', DEVC_ID='dTemp2' /
&VENT XB=0, 0, 10, 10.3, 2.1, 2.4, SURF_ID='HVAC', ID='IN2', COLOR='GRAY'/
&VENT XB=1.8, 1.8, 10, 10.3, 2.1, 2.4, SURF_ID='HVAC', ID='OUT2', UVW=0,0,0, COLOR='BLUE'/
&HVAC ID='IN2', TYPE_ID='NODE', DUCT_ID='JETFAN2', VENT_ID='IN2'/
&HVAC ID='OUT2', TYPE_ID='NODE', DUCT_ID='JETFAN2', VENT_ID='OUT2'/
&HVAC ID='JETFAN2', TYPE_ID='DUCT', NODE_ID='IN2','OUT2', VOLUME_FLOW=1.633, RAMP_ID='rampwent' /
```

W nowym podejściu w ogóle nie mamy SURF'ów, tylko podaje się unikalną nazwę surfa=HVAC.

W visualu musimy mieć możliwość ustawienia (pola):
- XB - tutaj może zrobię obsługę zmiany OBST'a, bo i tak już mam to dodasz jedynie metodę o nowej nazwie, 
- zamiennie, VOLUME FLOW / MASS FLOW,
- RAMP - taki sam jak wentylacyjny,
- zamiennie, AREA / DIAMETER / PARAMITER - jednakże domyślnie zostawiłbym AREA,
- temperatury zniszczenia, 
- UVW - kierownica na wyrzucie - wektor, 
- ukryte pole kierunku - otrzymujesz ode mnie z AC
- ID jeta

**Comment by milnicki3** [comment]
czyli co, kazdy egzemplarz jest definiowany calkowicie osobno czy robimy
jakis wspolny model np wydajnosc, srednica,  kierownice i tylko xb bedzie
rozne dla egzemplarzy?

27.04.2017 8:58 AM "fliszer" <notifications@github.com> napisał(a):

**Comment by fliszer** [comment]
Zastanawiam się, czy nie trzeba będzie zrobić guzika - Zastosuj do wszystkich, albo możliwość wybrania/zastosowania z bibliotecznych.

Na razie zróbmy dla każdego definiowalne osobno, a dodanie takiej funkcji nie spowoduje dużych zmian w kodzie. Musimy to przegadać na żywo.
