### ISSUE TITLE
Zła obsługa ROOM without door. 

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#47]
Żle utawione asserty w funkcji get_best_exit_from_room GEOM_DTO. Sprawdzenie czy pokój ma drzwi powinno odbywać się na poziomie sql. Obecnie wywala się nie pokazując jaki pokój jest problemem.

**Comment by mimooh** [comment]
> Żle utawione asserty w funkcji get_best_exit_from_room GEOM_DTO.
> Sprawdzenie czy pokój ma drzwi powinno odbywać się na poziomie sql.
> Obecnie wywala się nie pokazując jaki pokój jest problemem. 
Zgadza sie. Takie bledy powinny byc na etapie libSimoGeom wylapywane.
Przeniose.

get_best_exit_from_room() sadzac po nazwie samej i tak bedzie do
przepisania, bo ma to zwiazek z drugim bugiem: ludzie ewakuuja sie przez
zle wyjscie.

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
gotowe
