### ISSUE TITLE
Budowanie grafów przejść

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#48]
Jeżeli zostajemy przy grafach to trzeba byłoby poprawić ich generowanie. Mianowicie dla dużych pomieszczeń z kilkoma drzwiami dochodzi do sytuacji, gdy pedestrian stojący blisko jakiś drzwi idzie do zupełnie innych niż te najbliższe. Wynika to z tego, że na początku chyba @mimooh nie uwzględniasz odległości pedestriana od wyjścia w pomieszczeniu, przy budowaniu grafów. Czyli do kosztu całego grafu trzeba doliczyć dojście do pierwszych drzwi w pomieszczeniu. Jakby co mam wizualizację.

**Comment by mimooh** [comment]
> do zupełnie innych niż te najbliższe. Wynika to z tego, że na początku
> chyba @mimooh nie uwzględniasz odległości pedestriana od wyjścia w
> pomieszczeniu, przy budowaniu grafów. Czyli do kosztu całego grafu
Zgadza sie. Pomyslimy nad tym, bo faktycznie to moze stwarzac problemy.

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
gotowe
