### ISSUE TITLE
Przygotowanie pliku wsadowego dla eggmana

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#51]
@mimooh 
Wrzuciełem do devel/eggman/eggman.json propozycje pliku konfigurowalnego dla eggmana. Plik ten będzie generowany przez ulama. Zobacz Karlos na konwecję, czy mniej więcej jest ok. 
Plik generowany będzie do katalogu grid/projects/akrasuski/project_name/grid/1/eggman.json zamiast evac.json. Myślę, że to lepsza nazwa.

**Comment by mimooh** [comment]
gotowe

**Comment by akrasuski** [comment]
A gdzie ten plik leży?

**Comment by mimooh** [comment]
Tam gdzie chciales:
Plik generowany będzie do katalogu grid/projects/akrasuski/project_name/grid/1/eggman.json zamiast evac.json. Myślę, że to lepsza nazwa.

**Comment by akrasuski** [comment]
Zerknij jeszcze proszę na mój eggman.json w katalogu eggman. Część danych, które zamieściłeś jest niepotrzebna no i wydaje mi się, że lepsza nazwa na DUMP_DISTRIBUTIONS jest DUMP_DATA_FOR_VISUALISATION

**Comment by akrasuski** [comment]
Zabrakło też danych do RVO2 typu: TIME_STEP, RADIUS, TIME_HORIZON etc.

**Comment by mimooh** [comment]
DUMP_DISTRIBUTIONS to miala byc weryfikacja jakosci losowania w ulam.py.
Np, czy drzwi otwarte/zamkniete wylosowaly sie zgodnie z zalozeniami.
Jezeli zakladamy ze rozklady dzialaja poprawnie, to ta funkcja nei jest
potrzebna.

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
> Zabrakło też danych do RVO2 typu: TIME_STEP, RADIUS, TIME_HORIZON etc.
GENERAL to kiepskie miejsce na to. Proponuje 

RVO2['NEIGHBOR_DISTANCE']
RVO2['MAX_NEIGHBOR']
RVO2['NODE_RADIUS']
itd.

W ogole kiepsko to wychodzi ze w ten GENERAL cos wpada, cos wypada.
Musimy sie przyjrzec jakie parametry potrzebujemy i wtedy to zgrabnie
trzeba ulozyc.

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
gotowe
