### ISSUE TITLE
Wartość heat of combustion x 1000

### ISSUE THREAD

**Issue by akrasuski** [akrasuski/simo#8]
@mimooh 
Karlos jest błąd w heat of combustion podczas generowania pliku wejściowego dla CFASTA. Trafia wartość w kJ a powinna być J. Zatem trzeba pomnożyć to razy 1000.

**Comment by mimooh** [comment]
W mojej galezi sa takie rzedy wielkosci:

alfa (przez distributions.json):
{ "buildingCategory": "mall"       , "maxHRR": [1200 , 9000] , "alfaMinModeMax": [0.01 , 0.025 , 0.05] } ,
{ "buildingCategory": "hotel"      , "maxHRR": [1200 , 9000] , "alfaMinModeMax": [0.01 , 0.025 , 0.05] } ,
{ "buildingCategory": "university" , "maxHRR": [1200 , 9000] , "alfaMinModeMax": [0.01 , 0.025 , 0.05] }


hrr dla cfast.in:
[0, 78292, 313168, 704628, 1252672, 1957300, 2818512, 3836308, 5010688, 6341652, 7829200, 7858941, 7829200, 6341652, 5010688, 3836308, 2818512, 1957300, 1252672, 704628, 313168, 78292, 0]

Niedobrze?

-- 
Karol Kreński
tel. 517-302-055

**Comment by akrasuski** [comment]
To nie chodzi o HRR tylko o heat of combustion. To jest ostatni parametr w CHEMI
CHEMI,1, 1.8,0.3,0.05,0,0.283,19448.8
powinno być:
CHEMI,1, 1.8,0.3,0.05,0,0.283,19448800

**Comment by mimooh** [comment]
Linijka CHEMI to jest staly napis poki co. Nie wiem jak to sie generuje.

-- 
Karol Kreński
tel. 517-302-055

**Comment by akrasuski** [comment]
Ja mam w R tak:
 heat_of_combustion=round(runif(1,16400,27000),1);
jak to przepisałeś to powinieneś mieć tak samo.

powinno być natomiast: 
heat_of_combustion=round(runif(1,16400000,27000000),1);

**Comment by mimooh** [comment]
Done
